spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useSSL=false&serverTimezone=UTC
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  batch:
    initialize-schema: always
    job:
      enabled: true