version: 2
executorType: machine # needed for testcontainers
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/testcontainers-samples

    environment:
      JVM_OPTS: -Xmx4800m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: ./gradlew test